### ISSUE TITLE
Syntax issue with setup.py

### ISSUE THREAD

**Issue by alexandreday** [KlugerLab/FIt-SNE#19]
It looks like there is a syntax issue in the setup.py file for install the package via pip (Pypi). That is, if you try to install the most recent version of the package via `pip install fitsne`, you get the following error message:
```
 Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b3/j6sb_hk15t710xrbs7x3fvsc0000gn/T/pip-install-qebngw5i/fitsne/setup.py", line 16
        download_url=f"https://github.com/KlugerLab/pyFIt-SNE/archive/{__version__}.tar.gz"
                                                                                        ^
    SyntaxError: invalid syntax
```
The version number is missing. You need to write is as:

`"https://github.com/KlugerLab/pyFIt-SNE/archive/{"+__version__+"}.tar.gz"`

**Comment by alexandreday** [comment]
Moving comment to python wrapper repo !
