### ISSUE TITLE
Result.dat

### ISSUE THREAD

**Issue by JoeHEZHAO** [KlugerLab/FIt-SNE#58]
Hello 

Thanks for providing fit-tsne package. My question is when run fast-tsne in python, I can not find **result.dat** file in folder while I do have **data.dat**, which is not empty.

Can you provide some suggestions ??

Best
He Zhao

**Comment by dkobak** [comment]
Do you get any output from the fast_tsne python function? I guess you don't: the wrapper creates data.dat, calls the binary, and then something breaks. Do you get any console output? Please copy paste here.

**Comment by JoeHEZHAO** [comment]
Here is all error message:

=============== t-SNE v1.0.1 ===============
fast_tsne data_path: data.dat
fast_tsne result_path: result.dat
fast_tsne nthreads: 12
Memory allocation failed!
Traceback (most recent call last):
  File "fast_tsne_ucf101.py", line 34, in <module>

  File "/home/xxx/xxx/tsn-tensorflow/cnn_vis/fast_tsne.py", line 103, in fast_tsne
    with open(os.getcwd()+'/result.dat', 'rb') as f:
IOError: [Errno 2] No such file or directory: '/home/xxx/xxx/tsn-tensorflow/cnn_vis/result.dat'
